version: 1
directus: 10.12.1
vendor: sqlite
collections:
  - collection: global
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: global
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: true
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: global
  - collection: pages
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: pages
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: pages
fields:
  - collection: global
    field: id
    type: integer
    meta:
      collection: global
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: global
      data_type: integer
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: pages
    field: slug
    type: string
    meta:
      collection: pages
      conditions: null
      display: null
      display_options: null
      field: slug
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: slug
      table: pages
      data_type: varchar
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
relations:
  - collection: directus_settings
    field: public_registration_role
    related_collection: directus_roles
    meta: null
    schema:
      table: directus_settings
      column: public_registration_role
      foreign_key_table: directus_roles
      foreign_key_column: id
      constraint_name: null
      on_update: NO ACTION
      on_delete: SET NULL
  - collection: directus_webhooks
    field: migrated_flow
    related_collection: directus_flows
    meta: null
    schema:
      table: directus_webhooks
      column: migrated_flow
      foreign_key_table: directus_flows
      foreign_key_column: id
      constraint_name: null
      on_update: NO ACTION
      on_delete: SET NULL
